### ISSUE TITLE
Avoir un route /search/{search}

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/laragif#21]
Pour pouvoir partager des recherches

**Comment by ptitFicus** [comment]
C'est déjà plus ou moins le cas avec le système de route actuel non ?

**Comment by frinyvonnick** [comment]
Non on a une route /api/search/{search} qui nous renvoit le json de la recherche mais pas une route /search/{search} qui nous renvoit une page HTML 😄
